name: Create Release

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      new_version:
        required: true
        type: string
      project_name:
        required: true
        type: string

jobs:
  create_release:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    environment:
      name: ${{ inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get S3 website URL and output
        id: get_s3_url
        env: 
          BUCKET_NAME: ${{ inputs.project_name }}-${{ inputs.environment }}-v3
          VERSION: ${{ inputs.new_version }}
          REGION: ${{ secrets.AWS_REGION }}
        run: |
          # BUCKET_NAME="${{ inputs.project_name }}-${{ inputs.environment }}-v3"
          # VERSION=${{ inputs.new_version }}

          # Construct website URL
          WEBSITE_URL="http://$BUCKET_NAME.s3-website.$REGION.amazonaws.com/$VERSION/"

          echo "link=$WEBSITE_URL" >> $GITHUB_ENV

      - name: Generate release notes
        id: generate_release_notes
        run: |
          echo "## Release ${{ inputs.new_version }}" > release_notes.md
          echo "S3 Website URL: ${{ env.link }}" >> release_notes.md
          echo "" >> release_notes.md
          # Get all commits for the new release
          git log --pretty=format:"* %s" $(git describe --tags --abbrev=0 @^)..@ >> release_notes.md
          echo "" >> release_notes.md
          cat release_notes.md
          RELEASE_NOTES=$(cat release_notes.md)
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "$RELEASE_NOTES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update RELEASE.md
        run: |
          cat release_notes.md RELEASE.md > new_release.md
          mv new_release.md RELEASE.md
          cat RELEASE.md
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add RELEASE.md
          git commit -m "Update RELEASE.md for version ${{ inputs.new_version }}"
          git pull origin $(echo "${GITHUB_REF#refs/heads/}") --rebase
          git push origin HEAD:$(echo "${GITHUB_REF#refs/heads/}")

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ inputs.new_version }}
          release_name: Release ${{ inputs.new_version }}
          body: ${{ env.RELEASE_NOTES }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Compress dist folder
        run: zip -r dist.zip dist/

      - name: Upload dist folder to GitHub Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist.zip
          asset_name: dist.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}